server:
  port: 9293
  
spring:
  application:
    name: CONFIGSERVER
  cloud:
    discovery:
      enabled: true
    
    config:
     server:
        git:
          uri: https://github.com/Rex7/CloudConfig
          
          
          